
#ifndef GLOBALNATIVES_HEADER
#define GLOBALNATIVES_HEADER

//<Script module="Base" globaldecs="Other.xscript">
Declare_Native_Global(Native_operator_OSTimeInfo_Less_OSTimeInfo);
Declare_Native_Global(Native_operator_OSTimeInfo_Greater_OSTimeInfo);
Declare_Native_Global(Native_operator_OSTimeInfo_Equal_OSTimeInfo);
Declare_Native_Global(NativeGlobal_OSCreateDirectory);
Declare_Native_Global(NativeGlobal_OSFileExists);
Declare_Native_Global(NativeGlobal_OSGetFileTime);
Declare_Native_Global(NativeGlobal_OSAppHasFocus);
Declare_Native_Global(NativeGlobal_OSSetCursorPos);
Declare_Native_Global(NativeGlobal_OSGetCursorPos);
Declare_Native_Global(NativeGlobal_OSShowCursor);
Declare_Native_Global(NativeGlobal_EnumResources);
Declare_Native_Global(NativeGlobal_EnumFiles);
Declare_Native_Global(NativeGlobal_GetPathFileName);
Declare_Native_Global(NativeGlobal_GetPathDirectory);
Declare_Native_Global(NativeGlobal_GetPathWithoutExtension);
Declare_Native_Global(NativeGlobal_GetPathExtension);
Declare_Native_Global(NativeGlobal_Log);
Declare_Native_Global(NativeGlobal_EnableMemoryTracking);
Declare_Native_Global(NativeGlobal_EndProgram);
//</Script>

#endif

