//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Xed.rc
//
#define IDOK2                           3
#define IDC_OPENEXISTINGMODULE          3
#define IDCANCEL2                       4
#define IDC_CREATEMODULE                4
#define IDR_MENU1                       102
#define IDR_MAINMENU                    102
#define IDR_MENU2                       106
#define IDR_POPUPS                      106
#define IDD_DIALOG1                     107
#define IDD_VIEWPORTCONFIG              107
#define IDB_FOURPANEL                   109
#define IDB_FP                          109
#define IDB_HORIZONTALPAIR              110
#define IDB_HP                          110
#define IDB_VERTICLEPAIR                111
#define IDB_VP                          111
#define IDB_SINGLEBOTTOM_TOPPAIR        112
#define IDB_SBTP                        112
#define IDB_SINGLELEFT_RIGHTPAIR        113
#define IDB_SLRP                        113
#define IDB_SINGLEPANEL                 114
#define IDB_SP                          114
#define IDB_SINGLERIGHT_LEFTPAIR        115
#define IDB_SRLP                        115
#define IDB_SINGLETOP_BOTTOMPAIR        116
#define IDB_STBP                        116
#define IDI_ICON1                       118
#define IDD_RIGHTTOOLBAR                119
#define IDD_INDOORSIDEBAR               119
#define IDD_OPENLEVEL                   121
#define IDR_TOOLBAR1                    122
#define IDB_TOOLBAR_HIDEEDITOROBS       123
#define IDB_TOOLBAR_HIDEEDITOROBJS      123
#define IDR_MATERIALSMENU               124
#define IDB_TOOLBAR_REALTIMEIDB_TOOLBAR_REALTIME 124
#define IDB_TOOLBAR_REALTIME            124
#define IDD_NEWFOLDER                   125
#define IDD_UVEDIT                      128
#define IDR_OBJECTBROWSERMENU           131
#define IDD_SURFACEPROPERTIES           136
#define IDR_MAINACCELERATORS            137
#define IDR_SHAPEMENU                   138
#define IDD_CUSTOMSPLINEDETAIL          139
#define IDD_EXTRUDE                     140
#define IDD_SAVELEVEL                   141
#define IDD_OPENMODULE                  142
#define IDR_MESHBROWSERMENU             143
#define IDD_EDITORSETTINGS              144
#define IDR_PREFABBROWSERMENU           144
#define IDD_OUTDOORSIDEBAR              145
#define IDD_CREATEOUTDOOR               146
#define IDD_DIALOG2                     150
#define IDD_EDITBOXDIALOG               150
#define IDD_OCTLEVELSIDEBAR             151
#define IDR_SCRIPTMENU                  151
#define IDD_CREATEOCTLEVEL              152
#define IDD_PREFABSIDEBAR               153
#define IDD_STARTUPDIALOG               154
#define IDD_DIALOG3                     155
#define IDD_LOADMODULES                 155
#define IDD_CREATEMODULE                157
#define IDD_LIGHTMAPBOX                 158
#define IDD_STATUSBOX                   158
#define IDD_LIGHTMAPSETTINGS            159
#define IDD_ADDSEGMENTED                160
#define IDC_TREE1                       1001
#define IDC_OBJECTTREE                  1001
#define IDC_FP                          1002
#define IDC_HP                          1003
#define IDC_VP                          1004
#define IDC_MATERIALLIST                1004
#define IDC_SP                          1005
#define IDC_SRLP                        1006
#define IDC_STBP                        1007
#define IDC_MATERIAL                    1007
#define IDC_LEVELLIST                   1007
#define IDC_BUTTON7                     1008
#define IDC_SBTP                        1008
#define IDC_EDIT_MATERIALS              1008
#define IDC_ALIGNWALL                   1008
#define IDC_EDIT_SPLINEDETAIL           1008
#define IDC_SMOOTHANGLE                 1008
#define IDC_ALIGNFLOOR                  1009
#define IDC_SLRP                        1010
#define ID_MODE_SELECT                  1012
#define ID_MODIFY_SELECT                1012
#define ID_MODE_TERRAIN                 1013
#define ID_MODIFY_MOVE                  1013
#define ID_MODE_PREFABS                 1014
#define ID_MODIFY_ROTATE                1014
#define ID_GRID_SNAP                    1015
#define ID_GRID_INCREASE                1016
#define ID_GRID_INCREASE2               1017
#define ID_GRID_DECREASE                1017
#define ID_LIGHTMAPS_BUILD              1018
#define ID_LIGHTMAPS_REMOVE             1019
#define ID_CREATE_BOX                   1020
#define ID_PLACEPREFAB_FLOOR            1020
#define ID_TERRAIN_EDITOR               1021
#define ID_TERRAIN_RAISE                1021
#define ID_SELECTMODE_OBJECTS           1021
#define ID_PLACEPREFAB_DETAIL           1022
#define ID_BRUSH_SUBTRACT               1023
#define ID_TERRAIN_RAISE2               1023
#define ID_BRUSH_FLOOR                  1023
#define ID_BRUSH_ADD_GEOMETRY           1024
#define ID_BRUSH_SUBTRACT_GEOMETRY      1025
#define IDC_FOLDERNAME                  1026
#define ID_MODIFY_MOVE2                 1026
#define ID_MODIFY_MOVEPIVOT             1026
#define ID_TERRAIN_LOWER                1026
#define ID_SELECTMODE_WORLD             1026
#define IDC_FITTEXTURE                  1027
#define ID_TERRAIN_LEVEL                1027
#define ID_SELECTMODE_BRUSHES           1027
#define ID_MODE_CREATEBOX               1028
#define ID_TERRAIN_LOWER2               1028
#define ID_PLACEPREFAB_ALIGNED          1028
#define ID_MODE_CREATECYLINDER          1029
#define ID_TERRAIN_LEVEL2               1029
#define ID_GRID_CUSTOMGRID              1029
#define ID_GRID_DEFAULTGRID             1030
#define ID_PLAYERGRID_SHOW              1031
#define ID_ADJUSTY                      1031
#define ID_GRID_ADJUSTY                 1031
#define IDC_ROTATEANGLE                 1032
#define ID_GRID_RESETY                  1032
#define ID_PLACEOBJECT_DETAIL           1034
#define ID_BRUSH_IMPORT2                1035
#define ID_BRUSH_PLANE                  1035
#define ID_MODE_ENTITIES                1036
#define IDC_PANUP                       1036
#define ID_LIGHTMAPS_SETTINGS           1036
#define IDC_PANLEFT                     1037
#define IDC_PANDOWN                     1038
#define ID_PLACEOBJECT_ALIGNED          1038
#define IDC_PANRIGHT                    1039
#define ID_SELECTMODE_TEXTURES          1039
#define IDC_ROTATECLOCKWISE             1040
#define ID_LIGHTMAPS_DRAFT              1040
#define IDC_ROTATECCLOCKWISE            1041
#define IDC_SCALEAMOUNT                 1042
#define IDC_SCALEU                      1043
#define IDC_SCALEV                      1044
#define IDC_SCALEUV                     1045
#define IDC_HORIZONTALTILE              1047
#define IDC_VERTICALTILE                1048
#define IDC_PAN                         1049
#define IDC_SG1                         1050
#define IDC_SG2                         1051
#define IDC_SG3                         1052
#define IDC_SG4                         1053
#define IDC_SG5                         1054
#define IDC_SG6                         1055
#define IDC_SG7                         1056
#define IDC_SG8                         1057
#define IDC_SG9                         1058
#define IDC_SG10                        1059
#define IDC_SG11                        1060
#define IDC_SG12                        1061
#define IDC_SG13                        1062
#define IDC_SG14                        1063
#define IDC_SG15                        1064
#define IDC_SG16                        1065
#define IDC_SG17                        1066
#define IDC_SG18                        1067
#define IDC_SG19                        1068
#define IDC_SG20                        1069
#define IDC_SG21                        1070
#define IDC_SG22                        1071
#define IDC_SG23                        1072
#define IDC_SG24                        1073
#define IDC_SG25                        1074
#define IDC_SG26                        1075
#define IDC_SG27                        1076
#define IDC_SG28                        1077
#define IDC_SG29                        1078
#define IDC_SG30                        1079
#define IDC_SG31                        1080
#define IDC_SG32                        1081
#define IDC_EXTRUDEAMOUNT               1084
#define IDC_SMOOTHANGLE_SCROLLER        1086
#define IDC_TEXTURETOSMOOTHGROUPS       1088
#define IDC_FULLWRAPAROUND              1089
#define IDC_FACEUP                      1092
#define IDC_LEVELNAME                   1094
#define IDC_MODULELIST                  1096
#define IDC_GAMMASCROLL                 1099
#define IDC_GAMMAEDIT                   1100
#define IDC_BRIGHTNESSSCROLL            1103
#define IDC_TERRAINSIZE                 1104
#define IDC_CONTRASTSCROLL              1105
#define IDC_BRIGHTNESSEDIT              1106
#define IDC_HASWATER                    1106
#define IDC_CONTRASTEDIT                1107
#define IDC_BLOCKSIZE                   1108
#define IDC_BLOCKSIZESCROLLER           1109
#define IDC_COMBOBOXEX1                 1114
#define IDC_COMBO1                      1115
#define IDC_TEXSIZE                     1115
#define IDC_PHOTONMAPRESOLUTION         1115
#define IDC_ESTTEXSIZE                  1116
#define IDC_PHOTONMAPRESOLUTION2        1116
#define IDC_LMMULTIPLIER                1116
#define IDC_AREASIZE                    1118
#define IDC_DEFAULT_INDOOR              1119
#define IDC_DEFAULT_OCT                 1120
#define IDC_DEFAULT_OUTDOOR             1121
#define IDC_PREFABLIST                  1124
#define IDC_EDITBOX                     1125
#define IDC_ALIGNFLOORWALL              1126
#define IDC_ALIGNFLOORWALLSCROLLER      1127
#define IDC_SETASWORKINGMODULE          1135
#define IDC_AVAILABLEMODULES            1136
#define IDC_UP                          1137
#define IDC_LOADINGMODULES              1138
#define IDC_WORKINGMODULE               1139
#define IDC_INCLUDE                     1139
#define IDC_DOWN                        1140
#define IDC_LOAD                        1143
#define IDC_EXCLUDE                     1144
#define IDC_DESCRIPTION                 1146
#define IDC_NAME                        1149
#define IDC_MASTER                      1150
#define IDC_ADDON                       1151
#define IDC_FULLNAME                    1152
#define IDC_EXPORTMAPTEXTURES           1154
#define IDC_PROGRESS1                   1155
#define IDC_PROGRESS                    1155
#define IDC_ACTION                      1156
#define ID_BRUSH_IMPORT                 1157
#define IDC_ACTION2                     1157
#define IDC_BASICLIGHTING               1160
#define IDC_IBL                         1161
#define IDC_ENABLEGI                    1162
#define IDC_PASSCOUNT_SCROLLER          1163
#define IDC_PASSCOUNT                   1164
#define IDC_ENABLECF                    1165
#define IDC_BLURSHADOWS                 1166
#define IDC_MAXPHOTONDIST_SCROLLER      1167
#define IDC_MAXPHOTONDIST               1168
#define IDC_HIGHQUALITY                 1169
#define IDC_DECENTQUALITY               1170
#define IDC_BASICQUALITY                1171
#define IDC_COMPRESS                    1172
#define IDC_ENABLEAO                    1173
#define IDC_FASTQUALITY                 1174
#define IDC_MAXAODIST_SCROLLER          1175
#define IDC_MAXAODIST                   1176
#define IDC_SEGMENTSIZE_EDIT            1176
#define IDC_AOEXPONENT_SCROLLER         1177
#define IDC_SEGMENTSIZE                 1177
#define IDC_AOEXPONENT                  1178
#define IDC_RENDERAO                    1179
#define IDC_CUTCUBES                    1179
#define IDC_AODARKCUTOFF_SCROLLER       1180
#define IDC_CUTTERRAIN                  1180
#define IDC_AODARKCUTOFF                1181
#define IDC_ADDSEGMENTED                1181
#define ID_BRUSH_ADD_SEGMENTED          1181
#define ID_FILE_EXIT                    40004
#define ID_BUILD                        40005
#define ID_EDIT                         40006
#define ID_FILE_CLOSELEVEL              40009
#define ID_FILE_OPENLEVEL               40010
#define ID_FILE_NEWLEVEL                40011
#define ID_FRONT                        40012
#define ID_WIREFRAME                    40013
#define ID_VIEWPORT_BACK                40015
#define ID_VIEWPORT_FRONT               40016
#define ID_VIEWPORT_LEFT                40017
#define ID_VIEWPORT_RIGHT               40018
#define ID_VIEWPORT_TOP                 40019
#define ID_VIEWPORT_BOTTOM              40020
#define ID_VIEWPORT_MAIN                40021
#define ID_VIEWPORT_WIREFRAME           40022
#define ID_VIEWPORT_PLAYSOUND           40023
#define ID_VIEWPORT_SOUND               40024
#define ID_VIEW_VIEWPORTLAYOUT          40025
#define ID_VIEWPORT_CONFIGUREVIEWPORTS  40026
#define ID_VIEWPORT_SOLID               40027
#define ID_VIEWPORT_BOTH                40029
#define ID_VIEWPORT_SHOWGRID            40030
#define ID_FILE_SAVELEVEL               40032
#define ID_PRIMITIVES_BOX               40033
#define ID_FILE_BUILDLEVEL              40034
#define ID_BUTTON40045                  40045
#define ID_FILE_NEWINDOORLEVEL          40046
#define ID_FILE_NEWOUTDOORLEVEL         40047
#define ID_SCENE_PREFABS                40049
#define ID_Menu                         40050
#define ID_SCENE_SELECT                 40052
#define ID_SCENE_MOVE                   40053
#define ID_SCENE_ROTATE                 40054
#define ID_VIEWPORT_TEXTUREDONLY        40057
#define ID_VIEWPORT_FULLRENDERING       40058
#define ID_VIEWPORT_BRUSHES             40059
#define ID_BUILD_BUILDALL               40060
#define ID_BUILD_REBUILDSCENE           40061
#define ID_SCENE_MATERIALS              40062
#define ID_FILE_CREATEMATERIAL          40063
#define ID_FILE_EDITMATERIAL            40064
#define ID_FILE_DELETEMATERIAL          40065
#define ID_Menu40066                    40066
#define ID_MATERIAL_CREATE              40067
#define ID_MATERIAL_EDIT                40068
#define ID_MATERIAL_DELETE              40069
#define ID_MATERIAL_CLOSE               40072
#define ID_MATERIAL_NEWFOLDER           40073
#define ID_MATERIAL_REMOVEFOLDER        40074
#define ID_MATERIAL_RENAMEFOLDER        40081
#define ID_MATERIAL_RENAME              40082
#define ID_SCENE_BASICTEXTUREALIGNMENT  40088
#define ID_OBJECTS_OPENMODULE           40092
#define ID_OBJECTS_CLOSE                40093
#define ID_SCENE_OBJECTBROWSER          40094
#define ID_LEVELMESHCLICK_CREATELIGHT   40095
#define ID_CREATELIGHT_POINTLIGHT       40096
#define ID_CREATELIGHT_SPOTLIGHT        40097
#define ID_CREATELIGHT_DD               40098
#define ID_CREATELIGHT_DIRECTIONALLIGHT 40099
#define ID_LEVELMESHCLICK_CREATEOBJ     40100
#define ID_Menu40102                    40102
#define ID_LEVELMESHCLICK_TEXTUREALIGN  40104
#define ID_SCENE_OBJECTPROPERTIES       40105
#define ID_LEVELOBJECTCLICK_PROPERTIES  40106
#define ID_LEVELOBJECTCLICK_DELETE      40107
#define ID_Menu40109                    40109
#define ID_SCENE_ENABLESCENE            40110
#define ID_SCENE_SURFACEPROPERTIES      40111
#define ID_SCENE_UVMAPPING              40112
#define ID_LEVELMESHCLICK_SURFACEPROPERTIES 40113
#define ID_MYEDIT_UNDO                  40114
#define ID_MYEDIT_REDO                  40115
#define ID_MYEDIT_CUT                   40116
#define ID_MYEDIT_COPY                  40117
#define ID_MYEDIT_PASTE                 40118
#define ID_MYEDIT_DELETE                40119
#define ID_Menu40124                    40124
#define ID_SCENE_SHAPEEDITOR            40127
#define ID_SHAPEEDITOR_FILE_CLOSE       40128
#define ID_SHAPE_SPLINEDETAIL           40132
#define ID_SPLINEDETAIL_1               40133
#define ID_SPLINEDETAIL_2               40134
#define ID_SPLINEDETAIL_10              40136
#define ID_SPLINEDETAIL_15              40137
#define ID_SPLINEDETAIL_20              40138
#define ID_SPLINEDETAIL_CUSTOM          40139
#define ID_SHAPELINECLICK_INSERTVERTEX  40140
#define ID_SHAPEVERTCLICK_DELETEVERTEX  40141
#define ID_SPLINEDETAIL_5               40148
#define ID_SHAPEEDITOR_FILE_SAVE        40152
#define ID_SHAPEEDITOR_FILE_OPEN        40153
#define ID_SHAPEEDITOR_FILE_NEW         40154
#define ID_SHAPEEDITOR_FILE_SAVEAS      40157
#define ID_SHAPE_SPIN                   40159
#define ID_SHAPE_MAKESHEET              40160
#define ID_SHAPE_EXTRUDE                40161
#define ID_FILE_NEW40162                40162
#define ID_FILE_NEWOUTDOORLEVEL40163    40163
#define ID_BUILD_BUILDBSP               40164
#define ID_FILE_SAVELEVELAS             40165
#define ID_OBJECTS_UNLOADMODULE         40168
#define ID_FILE_IMPORT                  40169
#define ID_FILE_CLOSE40170              40170
#define ID_FILE_MAKEPREFAB              40171
#define ID_SCENE_MESHBROWSER            40172
#define ID_MESH_CLOSE                   40173
#define ID_MESH_MAKEPREFAB              40174
#define ID_MESH_IMPORT                  40175
#define ID_LEVELMESHCLICK_SELECTALLBRUSHFACES 40176
#define ID_FILE_SETTINGS                40177
#define ID_SPLINEDETAIL_11              40178
#define ID_SPLINEDETAIL_4               40179
#define ID_SPLINEDETAIL_3               40180
#define ID_FILE_NEWOCTLEVEL             40181
#define ID_SCENE_PREFABBROWSER          40182
#define ID_PREFAB_IMPORT                40183
#define ID_PREFAB_CLOSE                 40184
#define ID_PREFAB_NEWPREFAB             40185
#define ID_PREFAB_DUPLICATETEMPLATE     40186
#define ID_PREFAB_NEWPREFABTEMPLATE     40187
#define ID_PREFABFOLDER_DELETE          40188
#define ID_PREFABFOLDER_RENAME          40189
#define ID_PREFAB_NEWFOLDER             40190
#define ID_Menu40191                    40191
#define ID_LEVELMESHCLICK_ROTATE        40192
#define ID_LEVELMESHCLICK_MOVE          40193
#define ID_LEVELCLICK_MOVE              40194
#define ID_LEVELCLICK_ROTATE            40195
#define ID_LEVELMESHCLICK_WORLDPREFABMODE 40196
#define ID_LEVELMESHCLICK_DETAILPREFABMODE 40197
#define ID_LEVELCLICK_WORLDPREFABMODE   40198
#define ID_LEVELCLICK_DETAILPREFABMODE  40199
#define ID_LEVELCLICK_SELECTOBJECTS     40200
#define ID_LEVELCLICK_SELECTPREFABS     40201
#define ID_LEVELCLICK_SELECTBRUSHES     40202
#define ID_LEVELMESHCLICK_SELECTONLY    40203
#define ID_LEVELCLICK_SELECT            40204
#define ID_LEVELCLICK_SELECTONLY        40205
#define ID_LEVELOBJECTCLICK_SELECTTEXTURES 40206
#define ID_LEVELCLICK_SELECTTEXTURES    40207
#define ID_SCENE_HIDEEDITOROBJECTS      40208
#define ID_SCENE_OBJECTMODE             40209
#define ID_SCENE_SELECTOBJECTS          40210
#define ID_SCENE_SELECTPREFABS          40211
#define ID_SCENE_SELECTBRUSHES          40212
#define ID_SCENE_SELECTTEXTURES         40213
#define ID_MESH_BUILDBSP                40214
#define ID_PREFAB_DELETE                40215
#define ID_SCRIPT_SAVEASFILE            40216
#define ID_SCRIPT_SAVEASINTERAL         40217
#define ID_SCRIPT_CLOSE                 40218
#define ID_SCRIPT_SAVE                  40219
#define ID_SCRIPT_CLEAREVENTANDCLOSE    40220
#define ID_SCRIPT_ASSIGNSCRIPTFILETOTHISEVENT 40221
#define ID_CHECK                        40222
#define ID_SCRIPTCHECK                  40223
#define ID_EDIT_UNDO40224               40224
#define ID_EDIT_REDO40225               40225
#define ID_Menu40226                    40226
#define ID_FILE_SETACTIVEMODULE         40227
#define ID_FILE_NEWMODULE               40228
#define ID_FILE_LOADMODULE              40229
#define ID_FILE_SETACTIVEMODULES        40230
#define ID_LEVE_REBUILD                 40231
#define ID_LEVEL_REBUILDBRUSHES         40232
#define ID_LEVEL_REBUILDADDTIONBRUSHES  40233
#define ID_LEVEL_REBUILDADDITIONBRUSHES 40234
#define ID_LEVEL_REBUILDSUBTRACTIONBRUSHES 40235

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        161
#define _APS_NEXT_COMMAND_VALUE         40236
#define _APS_NEXT_CONTROL_VALUE         1182
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
